### ISSUE TITLE
Configuração Ambiente (Dantieris)

### ISSUE THREAD

**Issue by DiegoKremer** [Dantieris/ES3#1]
Configuração do ambiente no computador do Dantieris: Clone do projeto na máquina, importação para o Eclipse, importação das libs e execução do projeto.

**Comment by Dantieris** [comment]
Projeto foi clonado na máquina principal, importado no eclipse, as libs foram retiradas da instalação do  jogo pelo download normal e foi criado um arquivo .zip com as libs e compartilhado com o @DiegoKremer
