### ISSUE TITLE
Implementar teste para bug ao preencher o transporter

### ISSUE THREAD

**Issue by Dantieris** [Dantieris/ES3#13]
Implementar um unit test que represente o cenário de preencher um transporter com fertilizante.

**Comment by Dantieris** [comment]
Link para download do arquivo de save. https://drive.google.com/open?id=0Bxa3cYtnSxrpTXdoT1Myd0p2S3c

**Comment by Dantieris** [comment]
Resultado do teste passando 
![bugpreenchertransportersave](https://cloud.githubusercontent.com/assets/6727432/8356089/7d985c4e-1b29-11e5-9d79-22bf98660fda.png)

**Comment by DiegoKremer** [comment]
Teste de aceitação efetuado com sucesso.
